In [1]:
import numpy as np

A = np.array([[1, 3, 2], [5, 3, 1], [3, 4, 5]])
u, s, v = np.linalg.svd(A, full_matrices=True)
print("Left singular vectors:")
print(u.shape)
print()
print("Singular values:")
print(s)
print()
print("Right singular vectors:")
print(v.shape)

Left singular vectors:
(3, 3)

Singular values:
[9.34265841 3.24497827 1.08850813]

Right singular vectors:
(3, 3)


In [2]:
def rsvd(A, Omega):
    Y = A @ Omega
    Q, _ = np.linalg.qr(Y)
    B = Q.T @ A
    u_tilde, s, v = np.linalg.svd(B, full_matrices=False)
    u = Q @ u_tilde
    return u, s, v

In [3]:
np.random.seed(1000)
A = np.array([[1, 3, 2], [5, 3, 1], [3, 4, 5]])
rank = 2
Omega = np.random.randn(A.shape[1], rank)
u, s, v = rsvd(A, Omega)
print("Left singular vectors:")
print(u)
print()
print("Singular values:")
print(s)
print()
print("Right singular vectors:")
print(v)
print()

Left singular vectors:
[[ 0.38070859  0.60505354]
 [ 0.56830191 -0.74963644]
 [ 0.72944767  0.26824507]]

Singular values:
[9.34224023 3.02039888]

Right singular vectors:
[[ 0.57915029  0.61707064  0.53273704]
 [-0.77420021  0.21163814  0.59650929]]



In [1]:
import numpy as np


def power_iteration(A, Omega, power_iter=3):
    Y = A @ Omega
    for q in range(power_iter):
        Y = A @ (A.T @ Y)
    Q, _ = np.linalg.qr(Y)
    return Q

In [2]:
def rsvd(A, Omega):
    Q = power_iteration(A, Omega)
    B = Q.T @ A
    u_tilde, s, v = np.linalg.svd(B, full_matrices=False)
    u = Q @ u_tilde
    return u, s, v

In [5]:
np.random.seed(1000)
n = 5000
A = np.array([[1 / (i + j - 1) for j in range(1, n + 1)] for i in range(1, n + 1)])
rank = 2
Omega = np.random.randn(A.shape[1], rank)
u, s, v = rsvd(A, Omega)
print("Left singular vectors:")
print(u)
print()
print("Singular values:")
print(s)
print()
print("Right singular vectors:")
print(v)
print()

Left singular vectors:
[[ 0.36618079 -0.52861251]
 [ 0.25863536 -0.29493524]
 [ 0.21275975 -0.20390493]
 ...
 [ 0.00228615  0.00434915]
 [ 0.00228576  0.00434847]
 [ 0.00228537  0.00434779]]

Singular values:
[2.56793469 1.48886368]

Right singular vectors:
[[ 0.36616996  0.25863245  0.21275936 ...  0.00228602  0.00228563
   0.00228524]
 [-0.52901692 -0.29504224 -0.20391801 ...  0.00434437  0.00434369
   0.00434302]]

