In [1]:
import numpy as np

A = np.array([[1, 3, 2], [5, 3, 1], [3, 4, 5]])
u, s, v = np.linalg.svd(A, full_matrices=True)
print("Left singular vectors:")
print(u.shape)
print()
print("Singular values:")
print(s)
print()
print("Right singular vectors:")
print(v.shape)

Left singular vectors:
(3, 3)

Singular values:
[9.34265841 3.24497827 1.08850813]

Right singular vectors:
(3, 3)


In [2]:
def rsvd(A, Omega):
    Y = A @ Omega
    Q, _ = np.linalg.qr(Y)
    B = Q.T @ A
    u_tilde, s, v = np.linalg.svd(B, full_matrices=False)
    u = Q @ u_tilde
    return u, s, v

In [3]:
np.random.seed(1000)
A = np.array([[1, 3, 2], [5, 3, 1], [3, 4, 5]])
rank = 2
Omega = np.random.randn(A.shape[1], rank)
u, s, v = rsvd(A, Omega)
print("Left singular vectors:")
print(u)
print()
print("Singular values:")
print(s)
print()
print("Right singular vectors:")
print(v)
print()

Left singular vectors:
[[ 0.38070859  0.60505354]
 [ 0.56830191 -0.74963644]
 [ 0.72944767  0.26824507]]

Singular values:
[9.34224023 3.02039888]

Right singular vectors:
[[ 0.57915029  0.61707064  0.53273704]
 [-0.77420021  0.21163814  0.59650929]]



In [4]:
import numpy as np


def power_iteration(A, Omega, power_iter=3):
    Y = A @ Omega
    for q in range(power_iter):
        Y = A @ (A.T @ Y)
    Q, _ = np.linalg.qr(Y)
    return Q

In [5]:
def rsvd(A, Omega):
    Q = power_iteration(A, Omega)
    B = Q.T @ A
    u_tilde, s, v = np.linalg.svd(B, full_matrices=False)
    u = Q @ u_tilde
    return u, s, v

In [6]:
np.random.seed(1000)
A = np.array([[1, 3, 2], [5, 3, 1], [3, 4, 5]])
rank = 2
Omega = np.random.randn(A.shape[1], rank)
u, s, v = rsvd(A, Omega)
print("Left singular vectors:")
print(u)
print()
print("Singular values:")
print(s)
print()
print("Right singular vectors:")
print(v)
print()

Left singular vectors:
[[ 0.37421757  0.28528579]
 [ 0.56470638 -0.82484381]
 [ 0.73557319  0.48810317]]

Singular values:
[9.34265841 3.24497775]

Right singular vectors:
[[ 0.57847229  0.61642675  0.53421706]
 [-0.73178429  0.10284774  0.67373147]]

